on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Publish Site
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: jsumners/gh-action-hugo-deploy@master
        with:
          destination_repo: atlsynth/atlsynth.github.io
          destination_token: ${{ secrets.Deploy_Token }}
